version: 0.2

phases:
  install:
    commands:
      - yum update -y
      - yum install wget -y
      - yum install jq -y
  pre_build:
    commands:
      - echo Logging in to DockerHub...
      - docker login -u aman267 -p 123456789
      - echo Running the Qualys Container Security Sensor in CI/CD mode...
      - docker run -d --restart on-failure -v /var/run/docker.sock:/var/run/docker.sock:ro -v /etc/qualys:/usr/local/qualys/qpa/data/conf/agent-data -v /usr/local/qualys/sensor/data:/usr/local/qualys/qpa/data -e ACTIVATIONID=317e5b6e-9fa2-4728-8493-cbf7eea7e0e5 -e CUSTOMERID=c0328dc1-9289-43fd-8320-63a363ccfa40 -e POD_URL=https://cmsqagpublic.qg2.apps.qualys.com/ContainerSensor --net=host --name qualys-container-sensor qualys/qcs-sensor:latest --cicd-deployed-sensor
      - sleep 150
      - echo Logging in to Amazon ECR...
      - echo $AWS_DEFAULT_REGION
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date` 
      - docker pull aman267/version:latest
      - echo Extracting the Image ID for the docker image that is been built...
      - DOCKER_IMAGE_ID=$(docker images -q )
      - echo $DOCKER_IMAGE_ID
      - QUALYS_API_SERVER="https://qualysapi.qg2.apps.qualys.com"
      - USERNAME="csqua2aa"
      - PASSWORD="Hanuman$26797"
      - wget https://raw.githubusercontent.com/Qualys/community/master/containerSecurity/validate_image.sh --no-check-certificate
      - wget https://raw.githubusercontent.com/Qualys/community/master/containerSecurity/jq_filter.txt --no-check-certificate
      - chmod +x validate_image.sh
      - ./validate_image.sh ${QUALYS_API_SERVER} ${USERNAME} ${PASSWORD} ${DOCKER_IMAGE_ID}
      - sleep 200
      - tail -f /usr/local/qualys/sensor/data/logs/qpa.log
